// <auto-generated />
using System;
using BoardGameLibrary.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BoardGameLibrary.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(BoardGameLibraryDbContext))]
    [Migration("20260813200529_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BoardGameLibrary.Domain.BoardGames.BoardGame", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<int>("MaxPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("max_players");

                    b.Property<int>("MinPlayers")
                        .HasColumnType("integer")
                        .HasColumnName("min_players");

                    b.Property<int>("PlayingTimeMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("playing_time_minutes");

                    b.Property<int>("PublicationYear")
                        .HasColumnType("integer")
                        .HasColumnName("publication_year");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("publisher");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_board_games");

                    b.HasIndex("Title")
                        .HasDatabaseName("ix_board_games_title_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Title"), new[] { "gin_trgm_ops" });

                    b.ToTable("board_games", null, t =>
                        {
                            t.HasCheckConstraint("ck_board_games_max_players_range", "max_players BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_board_games_min_players_range", "min_players BETWEEN 1 AND 99");

                            t.HasCheckConstraint("ck_board_games_player_range", "max_players >= min_players");

                            t.HasCheckConstraint("ck_board_games_playing_time_minutes_range", "playing_time_minutes BETWEEN 1 AND 1440");

                            t.HasCheckConstraint("ck_board_games_publication_year_minimum", "publication_year >= 1900");

                            t.HasCheckConstraint("ck_board_games_publisher_not_blank", "char_length(btrim(publisher)) > 0");

                            t.HasCheckConstraint("ck_board_games_title_not_blank", "char_length(btrim(title)) > 0");
                        });
                });

            modelBuilder.Entity("BoardGameLibrary.Domain.Categories.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.HasIndex("Name")
                        .HasDatabaseName("ix_categories_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_categories_normalized_name");

                    b.ToTable("categories", null, t =>
                        {
                            t.HasCheckConstraint("ck_categories_name_not_blank", "char_length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_categories_normalized_name", "normalized_name = upper(btrim(name))");
                        });
                });

            modelBuilder.Entity("BoardGameLibrary.Domain.GameCopies.GameCopy", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly?>("AcquiredOn")
                        .HasColumnType("date")
                        .HasColumnName("acquired_on");

                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_game_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("condition");

                    b.Property<string>("InventoryCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("inventory_code");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.HasKey("Id")
                        .HasName("pk_game_copies");

                    b.HasIndex("BoardGameId")
                        .HasDatabaseName("ix_game_copies_board_game_id");

                    b.HasIndex("InventoryCode")
                        .IsUnique()
                        .HasDatabaseName("ux_game_copies_inventory_code");

                    b.ToTable("game_copies", null, t =>
                        {
                            t.HasCheckConstraint("ck_game_copies_condition", "condition IN ('Excellent', 'Good', 'Fair', 'Damaged')");

                            t.HasCheckConstraint("ck_game_copies_inventory_code_normalized", "inventory_code = upper(btrim(inventory_code))");

                            t.HasCheckConstraint("ck_game_copies_inventory_code_not_blank", "char_length(btrim(inventory_code)) > 0");
                        });
                });

            modelBuilder.Entity("BoardGameLibrary.Domain.Loans.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("DueAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at_utc");

                    b.Property<Guid>("GameCopyId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_copy_id");

                    b.Property<DateTimeOffset>("LoanedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("loaned_at_utc");

                    b.Property<Guid>("MemberId")
                        .HasColumnType("uuid")
                        .HasColumnName("member_id");

                    b.Property<DateTimeOffset?>("ReturnedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("returned_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_loans");

                    b.HasIndex("GameCopyId")
                        .IsUnique()
                        .HasDatabaseName("ux_loans_game_copy_id_open")
                        .HasFilter("returned_at_utc IS NULL");

                    b.HasIndex("LoanedAtUtc")
                        .HasDatabaseName("ix_loans_loaned_at_utc");

                    b.HasIndex("GameCopyId", "LoanedAtUtc")
                        .HasDatabaseName("ix_loans_game_copy_id_loaned_at_utc");

                    b.HasIndex("MemberId", "ReturnedAtUtc", "DueAtUtc")
                        .HasDatabaseName("ix_loans_member_id_returned_at_utc_due_at_utc");

                    b.ToTable("loans", null, t =>
                        {
                            t.HasCheckConstraint("ck_loans_fixed_lending_term", "EXTRACT(EPOCH FROM (due_at_utc - loaned_at_utc)) = 1209600");

                            t.HasCheckConstraint("ck_loans_returned_after_loaned", "returned_at_utc IS NULL OR returned_at_utc >= loaned_at_utc");
                        });
                });

            modelBuilder.Entity("BoardGameLibrary.Domain.Members.Member", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateOnly>("JoinedOn")
                        .HasColumnType("date")
                        .HasColumnName("joined_on");

                    b.Property<string>("MemberNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("member_number");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone_number");

                    b.HasKey("Id")
                        .HasName("pk_members");

                    b.HasIndex("Email")
                        .HasDatabaseName("ix_members_email_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Email"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Email"), new[] { "gin_trgm_ops" });

                    b.HasIndex("FullName")
                        .HasDatabaseName("ix_members_full_name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("FullName"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("FullName"), new[] { "gin_trgm_ops" });

                    b.HasIndex("MemberNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_members_member_number");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ux_members_normalized_email");

                    b.ToTable("members", null, t =>
                        {
                            t.HasCheckConstraint("ck_members_email_not_blank", "char_length(btrim(email)) > 0");

                            t.HasCheckConstraint("ck_members_full_name_not_blank", "char_length(btrim(full_name)) > 0");

                            t.HasCheckConstraint("ck_members_member_number_normalized", "member_number = upper(btrim(member_number))");

                            t.HasCheckConstraint("ck_members_member_number_not_blank", "char_length(btrim(member_number)) > 0");

                            t.HasCheckConstraint("ck_members_normalized_email", "normalized_email = upper(btrim(email))");

                            t.HasCheckConstraint("ck_members_phone_number_not_blank", "phone_number IS NULL OR char_length(btrim(phone_number)) > 0");
                        });
                });

            modelBuilder.Entity("BoardGameLibrary.Infrastructure.Persistence.Models.BoardGameCategory", b =>
                {
                    b.Property<Guid>("BoardGameId")
                        .HasColumnType("uuid")
                        .HasColumnName("board_game_id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.HasKey("BoardGameId", "CategoryId")
                        .HasName("pk_board_game_categories");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_board_game_categories_category_id");

                    b.ToTable("board_game_categories", (string)null);
                });

            modelBuilder.Entity("BoardGameLibrary.Domain.GameCopies.GameCopy", b =>
                {
                    b.HasOne("BoardGameLibrary.Domain.BoardGames.BoardGame", null)
                        .WithMany()
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_game_copies_board_games_board_game_id");
                });

            modelBuilder.Entity("BoardGameLibrary.Domain.Loans.Loan", b =>
                {
                    b.HasOne("BoardGameLibrary.Domain.GameCopies.GameCopy", null)
                        .WithMany()
                        .HasForeignKey("GameCopyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_loans_game_copies_game_copy_id");

                    b.HasOne("BoardGameLibrary.Domain.Members.Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_loans_members_member_id");
                });

            modelBuilder.Entity("BoardGameLibrary.Infrastructure.Persistence.Models.BoardGameCategory", b =>
                {
                    b.HasOne("BoardGameLibrary.Domain.BoardGames.BoardGame", null)
                        .WithMany()
                        .HasForeignKey("BoardGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_board_game_categories_board_games_board_game_id");

                    b.HasOne("BoardGameLibrary.Domain.Categories.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_board_game_categories_categories_category_id");
                });
#pragma warning restore 612, 618
        }
    }
}
